### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by patiwat-w** [primefactorgit/DEVES.IntegrationAPI#47]
พบ error ที่คาดว่าน่าจะเกิดขึ้นในขั้นตอน log
-------------------------------------------------------------------------------------------

TransactionId:01-17090510444-0007932
MachineName:CRM-APP01

Date:9/5/2017 10:04:44 AM

Message:An item with the same key has already been added.

Source:mscorlib

Url:http://crmapi.deves.co.th/claim-service/api/UpdateClaimInfo

Method:POST

------------------------------------
Headers
------------------------------------
[{"Key":"Host","Value":["crmapi.deves.co.th"]},{"Key":"User-Agent","Value":["Jakarta","Commons-HttpClient/3.1"]}]

------------------------------------
Request Context
------------------------------------
{"claimNo":"V0664851","highLossCaseFlag":"N","ticketNo":"CAS201707-08574","claimNotiNo":"1707-07191","legalCaseFlag":"N","vipCaseFlag":"N","claimStatusCode":"4","claimStatusDesc":"อนุมัติแล้วปรับยอดแล้ว (Adjusted)"}

------------------------------------
Response Content
------------------------------------
{"code":"500","message":"An error occurred","description":"An item with the same key has already been added.","transactionId":"01-17090510444-0007932","transactionDateTime":"2017-09-05 10:04:44","stackTrace":""}

------------------------------------
ExceptionContext
------------------------------------
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at DEVES.IntegrationAPI.WebApi.TechnicalService.GlobalTransactionIdGenerator.GetNewGuid()
   at DEVES.IntegrationAPI.WebApi.TechnicalService.ApiLogHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Owin.PassiveAuthenticationMessageHandler.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()

------------------------------------
Inner Exception
------------------------------------

------------------------------------
Inner Exception
------------------------------------

**Comment by patiwat-w** [comment]
แก้ไขแล้วโดยเพิ่ม เวลาระดับ มิลลิวินาที ลงไปใน transactionLog และ ให้ระบบเช็คก่อนว่า Id ที่สร้างขึ้นซ้ำหรือไม่ ภายใน application เดียวกัน
